from __future__ import annotations

HIT_EFFECT_CSS = r"""
.impactLayer {
  position: absolute !important;
  inset: 0 !important;
  width: 1920px !important;
  height: 1080px !important;
  overflow: hidden !important;
  pointer-events: none !important;
  z-index: 999 !important;
  transform: none !important;
}
#impactCanvas {
  position: absolute;
  inset: 0;
  width: 1920px;
  height: 1080px;
  display: block;
  pointer-events: none;
}
.recent { display: none !important; }
"""

HIT_EFFECT_HTML = (
    '<div id="impactLayer" class="impactLayer">'
    '<canvas id="impactCanvas" width="1920" height="1080"></canvas>'
    "</div>"
)

HIT_EFFECT_JS = r"""
function impactNum(v){var n=Number(v);return isFinite(n)?n:null}
function impactClamp(v){v=Number(v)||0;return Math.max(0,Math.min(1,v))}
var impactState={lastAt:0,lastX:-10,lastY:-10,max:10,effects:[],raf:0,ctx:null};
function overlayBeacon(event,extra){try{extra=extra||{};var p=new URLSearchParams();p.set('event',String(event||''));p.set('seq',String(lastSeq||0));if(extra.key)p.set('key',String(extra.key).slice(0,240));if(extra.browserMs!=null)p.set('browserMs',String(extra.browserMs));if(extra.pushMs!=null)p.set('pushMs',String(extra.pushMs));fetch('/beacon?'+p.toString(),{cache:'no-store',keepalive:true}).catch(function(){})}catch(e){}}
function impactPos(ev){var sx=impactNum(ev&&ev.screenX),sy=impactNum(ev&&ev.screenY);if(sx===null||sy===null)return null;return{x:impactClamp(sx),y:impactClamp(1-sy)}}
function impactCls(ev){var dmg=Number(ev&&ev.damage)||0,k=String(ev&&ev.effectKind||'').toLowerCase(),w=String(ev&&ev.weakPoint||'').toLowerCase();if(k.indexOf('knock')>=0||k==='tko'||k==='down')return'down';if(k.indexOf('stun')>=0)return'stun';if(w&&w!=='none')return'weak';if(dmg>=60)return'high';if(dmg>=28)return'mid';return'low'}
function impactCfgNum(v,f,minv,maxv){v=Number(v);if(!isFinite(v))v=f;if(minv!==undefined)v=Math.max(minv,v);if(maxv!==undefined)v=Math.min(maxv,v);return v}
function impactSize(cls,dmg){var base=impactCfgNum(latestState.hitFxBaseSize,86,24,240),scale=impactCfgNum(latestState.hitFxDamageScale,.42,0,3),mult={low:.82,mid:1.04,high:1.25,weak:1.16,stun:1.42,down:1.58}[cls]||1;return Math.max(30,Math.min(260,base*mult+(Number(dmg)||0)*scale))}
function impactHex(v,f){v=String(v||'').trim();return /^#[0-9a-fA-F]{6}$/.test(v)?v:f}
function impactRgb(hex){hex=impactHex(hex,'#ffaa55');return{r:parseInt(hex.slice(1,3),16),g:parseInt(hex.slice(3,5),16),b:parseInt(hex.slice(5,7),16)}}
function impactMix(rgb,t){return{r:Math.round(rgb.r+(255-rgb.r)*t),g:Math.round(rgb.g+(255-rgb.g)*t),b:Math.round(rgb.b+(255-rgb.b)*t)}}
function impactRgba(rgb,a){return'rgba('+rgb.r+','+rgb.g+','+rgb.b+','+Math.max(0,Math.min(1,a))+')'}
function impactPresetColor(cls){var preset=String(latestState.hitFxColorPreset||'classic').toLowerCase(),map={classic:{low:'#38bdf8',mid:'#fb923c',high:'#f87171',weak:'#facc15',stun:'#ef4444',down:'#ef4444'},icefire:{low:'#60a5fa',mid:'#f59e0b',high:'#ef4444',weak:'#fde047',stun:'#dc2626',down:'#dc2626'},neon:{low:'#22d3ee',mid:'#a3e635',high:'#fb7185',weak:'#facc15',stun:'#f97316',down:'#ef4444'},custom:{low:impactHex(latestState.hitFxColorLow,'#38bdf8'),mid:impactHex(latestState.hitFxColorMid,'#fb923c'),high:impactHex(latestState.hitFxColorHigh,'#f87171'),weak:impactHex(latestState.hitFxColorWeak,'#facc15'),stun:impactHex(latestState.hitFxColorStun,'#ef4444'),down:impactHex(latestState.hitFxColorStun,'#ef4444')}};var pal=map[preset]||map.classic;return pal[cls]||pal.high}
function impactRand(seed){var x=Math.sin(seed*12.9898+78.233)*43758.5453;return x-Math.floor(x)}
function impactEaseOut(v){v=Math.max(0,Math.min(1,v));return 1-Math.pow(1-v,3)}
function impactAngle(ev,seed){var side=String(ev&&ev.side||'').toLowerCase(),hand=String(ev&&ev.hand||ev&&ev.punchHand||'').toLowerCase(),punch=String(ev&&ev.punch||ev&&ev.punchType||ev&&ev.type||'').toLowerCase(),a=side==='blue'?Math.PI:0;if(punch.indexOf('upper')>=0)a=side==='blue'?-2.15:-.99;else if(punch.indexOf('hook')>=0)a=side==='blue'?-2.78:-.36;else if(punch.indexOf('over')>=0)a=side==='blue'?2.62:.52;if(hand.indexOf('left')>=0)a-=.10;else if(hand.indexOf('right')>=0)a+=.10;return a+(impactRand(seed)-.5)*.18}
function impactLabel(ev,dmg){var cm=Number(ev&&ev.counterMult)||1;if(cm>1.0001)return'COUNTER '+cm.toFixed(2)+'x';if(dmg>0)return String(Math.round(dmg));var weak=String(ev&&ev.weakPoint||'').trim();return weak&&weak.toLowerCase()!=='none'?weak.slice(0,8):'HIT'}
function impactParticles(cls,seed,angle,size){var count={low:5,mid:8,high:12,weak:10,stun:15,down:18}[cls]||8,out=[];for(var i=0;i<count;i++){var r1=impactRand(seed+i*7.13),r2=impactRand(seed+i*13.71),spread=(r1-.5)*(cls==='stun'?2.0:1.35);out.push({a:angle+spread,len:size*(.28+r2*.78),width:Math.max(1.2,size*(.012+r1*.024)),speed:.72+r2*.65,spin:(r1-.5)*.8})}return out}
function impactCanvasContext(){if(impactState.ctx)return impactState.ctx;var c=q('impactCanvas');if(!c)return null;impactState.ctx=c.getContext('2d',{alpha:true,desynchronized:true});return impactState.ctx}
function impactPoly(ctx,points,fill){ctx.beginPath();ctx.moveTo(points[0][0],points[0][1]);for(var i=1;i<points.length;i++)ctx.lineTo(points[i][0],points[i][1]);ctx.closePath();ctx.fillStyle=fill;ctx.fill()}
function impactBlade(ctx,e,burst,alpha){var size=e.size,dx=Math.cos(e.angle),dy=Math.sin(e.angle),px=-dy,py=dx,tail=size*(.58+burst*.82),head=size*(.18+burst*.18),wide=size*(.055+burst*.035),base=e.base,hot=e.hot;ctx.save();ctx.translate(e.x,e.y);ctx.globalCompositeOperation='source-over';ctx.shadowColor=impactRgba(base,.9*alpha);ctx.shadowBlur=12*e.glow;impactPoly(ctx,[[-dx*tail+px*wide,-dy*tail+py*wide],[dx*head+px*wide*.22,dy*head+py*wide*.22],[dx*head*1.55,dy*head*1.55],[-dx*tail-px*wide,-dy*tail-py*wide]],impactRgba(base,.9*alpha));impactPoly(ctx,[[-dx*tail*.62+px*wide*.28,-dy*tail*.62+py*wide*.28],[dx*head*1.3,dy*head*1.3],[-dx*tail*.62-px*wide*.28,-dy*tail*.62-py*wide*.28]],impactRgba(hot,.98*alpha));ctx.restore()}
function impactCore(ctx,e,burst,alpha){var s=e.size*(.16+.22*burst),a=e.angle,dx=Math.cos(a),dy=Math.sin(a),px=-dy,py=dx,base=e.base,hot=e.hot;ctx.save();ctx.translate(e.x,e.y);ctx.globalCompositeOperation='source-over';ctx.shadowColor=impactRgba(base,.95*alpha);ctx.shadowBlur=(10+e.size*.12)*e.glow;impactPoly(ctx,[[dx*s*1.55,dy*s*1.55],[px*s*.34,py*s*.34],[-dx*s*.9,-dy*s*.9],[-px*s*.34,-py*s*.34]],impactRgba(hot,e.fill*alpha));impactPoly(ctx,[[dx*s*.78,dy*s*.78],[px*s*.16,py*s*.16],[-dx*s*.42,-dy*s*.42],[-px*s*.16,-py*s*.16]],impactRgba({r:255,g:255,b:255},.95*alpha));ctx.restore()}
function impactShards(ctx,e,burst,alpha){if(!e.spriteOn)return;ctx.save();ctx.translate(e.x,e.y);ctx.globalCompositeOperation='source-over';ctx.shadowColor=impactRgba(e.base,.78*alpha);ctx.shadowBlur=6*e.glow;for(var i=0;i<e.particles.length;i++){var p=e.particles[i],travel=p.len*impactEaseOut(Math.min(1,burst*p.speed)),ca=Math.cos(p.a),sa=Math.sin(p.a),tip=travel,tail=Math.max(3,travel-e.size*(.12+.22*(1-burst))),w=p.width*(1-burst*.45);impactPoly(ctx,[[ca*tip,sa*tip],[ca*tail-sa*w,sa*tail+ca*w],[ca*(tail-e.size*.05),sa*(tail-e.size*.05)],[ca*tail+sa*w,sa*tail-ca*w]],impactRgba(i%3===0?e.hot:e.base,(.94-i/e.particles.length*.25)*alpha))}ctx.restore()}
function impactChevrons(ctx,e,burst,alpha){if(!e.ringOn)return;var dist=e.size*(.20+.55*burst),span=e.size*(.18+.16*burst),a=e.angle,dx=Math.cos(a),dy=Math.sin(a),px=-dy,py=dx,lw=e.ringWidth;ctx.save();ctx.translate(e.x,e.y);ctx.globalCompositeOperation='source-over';ctx.lineCap='square';ctx.lineJoin='miter';ctx.strokeStyle=impactRgba(e.hot,.9*alpha);ctx.lineWidth=lw;ctx.shadowColor=impactRgba(e.base,.82*alpha);ctx.shadowBlur=8*e.glow;for(var sign=-1;sign<=1;sign+=2){var cx=px*dist*sign,cy=py*dist*sign;ctx.beginPath();ctx.moveTo(cx-dx*span-px*span*.26*sign,cy-dy*span-py*span*.26*sign);ctx.lineTo(cx+px*span*.20*sign,cy+py*span*.20*sign);ctx.lineTo(cx+dx*span-px*span*.26*sign,cy+dy*span-py*span*.26*sign);ctx.stroke()}ctx.restore()}
function impactCracks(ctx,e,burst,alpha){if(e.cls!=='weak'&&e.cls!=='stun'&&e.cls!=='down')return;var branches=e.cls==='weak'?5:8;ctx.save();ctx.translate(e.x,e.y);ctx.globalCompositeOperation='source-over';ctx.strokeStyle=impactRgba(e.hot,.94*alpha);ctx.lineWidth=Math.max(1.3,e.ringWidth*.55);ctx.shadowColor=impactRgba(e.base,.9*alpha);ctx.shadowBlur=7*e.glow;for(var i=0;i<branches;i++){var a=e.angle+(i/(branches-1)-.5)*(e.cls==='weak'?2.2:3.5)+(impactRand(e.seed+i*23)-.5)*.35,len=e.size*(.18+.42*impactRand(e.seed+i*31))*burst,x1=Math.cos(a)*len*.42,y1=Math.sin(a)*len*.42,x2=Math.cos(a+.18*(i%2?1:-1))*len,y2=Math.sin(a+.18*(i%2?1:-1))*len;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()}ctx.restore()}
function impactText(ctx,e,burst,alpha){if(!e.showText)return;var side=String(e.side||'').toLowerCase(),dir=side==='blue'?1:-1,x=e.x+dir*e.size*.28,y=e.y-e.size*.38,fontSize=Math.max(20,Math.min(58,e.size*.27*e.textScale)),kick=(1-burst)*e.size*.18;ctx.save();ctx.translate(x+dir*kick,y);ctx.scale(.84+.16*burst,.84+.16*burst);ctx.globalAlpha=Math.min(1,alpha*1.08);ctx.font='900 '+fontSize.toFixed(1)+'px "Bahnschrift Condensed","Arial Narrow",sans-serif';ctx.textAlign=side==='blue'?'left':'right';ctx.textBaseline='middle';ctx.lineJoin='miter';ctx.miterLimit=3;ctx.strokeStyle='rgba(0,0,0,.92)';ctx.lineWidth=Math.max(3,fontSize*.16);ctx.strokeText(e.label,0,0);ctx.shadowColor=impactRgba(e.base,.95);ctx.shadowBlur=10*e.glow;ctx.fillStyle=impactRgba(e.hot,1);ctx.fillText(e.label,0,0);ctx.restore()}
function drawScreenImpact(ctx,e,now){var age=now-e.started,dur=e.duration,t=Math.max(0,Math.min(1,age/dur)),burst=impactEaseOut(Math.min(1,age/e.popMs)),fade=t<.42?1:Math.max(0,(1-t)/.58),alpha=Math.min(1,e.opacity)*fade;impactBlade(ctx,e,burst,alpha);impactChevrons(ctx,e,burst,alpha);impactShards(ctx,e,burst,alpha);impactCracks(ctx,e,burst,alpha);impactCore(ctx,e,burst,alpha);impactText(ctx,e,burst,alpha);return age<dur}
function renderImpactFrame(now){impactState.raf=0;var ctx=impactCanvasContext();if(!ctx)return;ctx.clearRect(0,0,1920,1080);var active=[];for(var i=0;i<impactState.effects.length;i++){var e=impactState.effects[i];if(drawScreenImpact(ctx,e,now))active.push(e)}impactState.effects=active;if(active.length)impactState.raf=requestAnimationFrame(renderImpactFrame)}
function showScreenImpact(ev){var p=impactPos(ev),ctx=impactCanvasContext();if(!p||!ctx)return;var now=(performance&&performance.now)?performance.now():Date.now();if(now-impactState.lastAt<16&&Math.abs(p.x-impactState.lastX)<.008&&Math.abs(p.y-impactState.lastY)<.012)return;impactState.lastAt=now;impactState.lastX=p.x;impactState.lastY=p.y;var cls=impactCls(ev),dmg=Number(ev&&ev.damage)||0,dur=Math.round(impactCfgNum(latestState.hitFxDurationMs,170,80,1200)),popMs=Math.round(impactCfgNum(latestState.hitFxPopMs,58,20,280)),seed=(Number(ev&&ev.id)||0)*37+dmg*11+(p.x*991+p.y*577),base=impactRgb(impactPresetColor(cls)),e={x:p.x*1920,y:p.y*1080,side:String(ev&&ev.side||''),cls:cls,damage:dmg,duration:dur,popMs:Math.min(popMs,dur*.72),started:now,seed:seed,size:impactSize(cls,dmg),angle:impactAngle(ev,seed),base:base,hot:impactMix(base,.78),opacity:impactCfgNum(latestState.hitFxOpacity,1,.05,1.5),glow:impactCfgNum(latestState.hitFxGlow,1,0,3),fill:impactCfgNum(latestState.hitFxFillOpacity,1,0,1.5),ringWidth:impactCfgNum(latestState.hitFxRingWidth,4,1,20),textScale:impactCfgNum(latestState.hitFxTextScale,1,.5,2),showText:latestState.hitFxShowText!==false,spriteOn:latestState.hitFxSpriteEnabled!==false,ringOn:latestState.hitFxRingEnabled!==false,label:impactLabel(ev,dmg)};e.particles=impactParticles(cls,seed,e.angle,e.size);impactState.effects.push(e);if(impactState.effects.length>impactState.max)impactState.effects.splice(0,impactState.effects.length-impactState.max);if(!impactState.raf)impactState.raf=requestAnimationFrame(renderImpactFrame);try{if(latestState.hitFxLatencyLog!==false&&console&&console.info){var showMs=(performance&&performance.now)?performance.now():Date.now(),pushMs=Number(ev&&ev.pushPerfMs)||0;console.info('[HITFX_BROWSER_SHOW] key='+(ev&&ev.hitfxKey||'')+' dmg='+dmg+' x='+p.x.toFixed(4)+' y='+p.y.toFixed(4)+' browser_show_ms='+showMs.toFixed(1)+' push_perf_ms='+pushMs.toFixed(1));overlayBeacon('hitfx_show',{key:(ev&&ev.hitfxKey)||'',browserMs:showMs.toFixed(1),pushMs:pushMs.toFixed(1)})}}catch(err){}}
"""
